[book]
title = "Project Universe"
authors = ["Shaostoul"]
description = "Project Universe is a free, public-domain sci-fi fantasy simulation RPG, developed by Shaostoul's global community of volunteers, dedicated to empowering individuals and communities through unconventional, low-cost solutions in hopes of peacefully uniting humanity."
language = "en"
multilingual = false
src = "Project Universe"

[build]
build-dir = "book"  # Specifies where the final output will be stored

[output.html]
default-theme = "dark"  # Dark theme for the book
default-highlighting = "base16-ocean-dark"  # Dark-themed syntax highlighting for code blocks
mathjax-support = true  # Enables MathJax for mathematical formulas

[output.html.search]
enable = true  # Enables search functionality for HTML output

[output.html.fold]
enable = true  # Enables the ability to fold sections (like accordions)
